INSERT INTO LOCATION (LOC_ID,LOC_CITY, LOC_COUNTRY) VALUES 
(1,'Lebowakgomo','South Africa'),
(2,'Potchefstroom','South Africa'),
(3,'Graaff Reinet','South Africa'),
(4,'Rustenburg','South Africa'),
(5,'Brandfort','South Africa'),
(6,'Vryheid','South Africa'),
(7,'Vereeniging','South Africa'),
(8,'Brits','South Africa'),
(9,'Bethlehem','South Africa'),
(10,'Ubomba','South Africa'),
(11,'Polokwane','South Africa'),
(12,'Springbok','South Africa'),
(13,'Thohoyandou','South Africa'),
(14,'Pietermaritzburg','South Africa'),
(15,'Poffader','South Africa'),
(16,'Carnarvon','South Africa'),
(17,'Kroonstad','South Africa'),
(18,'Alexander Bay','South Africa'),
(19,'Bloemhof','South Africa'),
(20,'Hermanus','South Africa'),
(21,'Bethal','South Africa'),
(22,'Upington','South Africa'),
(23,'Tzaneen','South Africa'),
(24,'Vanhynsdorp','South Africa'),
(25,'Kimberley','South Africa'),
(26,'Durban','South Africa'),
(27,'Klerksdorp','South Africa'),
(28,'Welkom','South Africa'),
(29,'De Aar','South Africa'),
(30,'Prieska','South Africa'),
(31,'Saldanha','South Africa'),
(32,'Middelburg','South Africa'),
(33,'Port St. Johns','South Africa'),
(34,'Volksrust','South Africa'),
(35,'Ulundi','South Africa'),
(36,'Beaufort West','South Africa'),
(37,'Komatipoort','South Africa'),
(38,'Nelspruit','South Africa'),
(39,'Standerton','South Africa'),
(40,'Johannesburg','South Africa'),
(41,'Kuruman','South Africa'),
(42,'Paarl','South Africa'),
(43,'Worcester','South Africa'),
(44,'Colesberg','South Africa'),
(45,'Umtata','South Africa'),
(46,'Aliwal North','South Africa'),
(47,'Middelburg','South Africa'),
(48,'Springs','South Africa'),
(49,'Benoni','South Africa'),
(50,'Port Shepstone','South Africa'),
(51,'Oudtshoorn','South Africa'),
(52,'Port Elizabeth','South Africa'),
(53,'Port Alfred','South Africa'),
(54,'East London','South Africa'),
(55,'Mossel Bay','South Africa'),
(56,'Vryburg','South Africa'),
(57,'Uitenhage','South Africa'),
(58,'Bhisho','South Africa'),
(59,'Knysna','South Africa'),
(60,'Queenstown','South Africa'),
(61,'Cradock','South Africa'),
(62,'Bredasdorp','South Africa'),
(63,'Swellendam','South Africa'),
(64,'Ladysmith','South Africa'),
(65,'George','South Africa'),
(66,'Grahamstown','South Africa'),
(67,'Mmabatho','South Africa'),
(68,'Mahikeng','South Africa'),
(69,'Musina','South Africa'),
(70,'Pretoria','South Africa'),
(71,'Bloemfontein','South Africa'),
(72,'Cape Town','South Africa'),
(73,'Chaguaramas','Venezuela'),
(74,'El Dorado','Venezuela'),
(75,'El Manteco','Venezuela'),
(76,'Caracas','Venezuela'),
(77,'Barcelona','Venezuela'),
(78,'Barinas','Venezuela'),
(79,'Barquisimeto','Venezuela'),
(80,'Ciudad Bolivar','Venezuela'),
(81,'Coro','Venezuela'),
(82,'Cumana','Venezuela'),
(83,'Guanare','Venezuela'),
(84,'La Guaira','Venezuela'),
(85,'Los Teques','Venezuela'),
(86,'Maracaibo','Venezuela'),
(87,'Maracay','Venezuela'),
(88,'Maturin','Venezuela'),
(89,'Merida','Venezuela'),
(90,'San Carlos','Venezuela'),
(91,'San Cristobal','Venezuela'),
(92,'San Felipe','Venezuela'),
(93,'San Fernando de Apure','Venezuela'),
(94,'San Juan De Los Morros','Venezuela'),
(95,'Trujillo','Venezuela'),
(96,'Tucupita','Venezuela'),
(97,'Valencia','Venezuela'),
(98,'Puerto Ayacucho','Venezuela'),
(99,'La Asuncion','Venezuela'),
(100,'El Tigre','Venezuela'),
(101,'Ciudad Guayana','Venezuela'),
(102,'Upata','Venezuela'),
(103,'Puerto la Cruz','Venezuela'),
(104,'Anaco','Venezuela'),
(105,'Porlamar','Venezuela'),
(106,'La Esmeralda','Venezuela'),
(107,'Guasdualito','Venezuela'),
(108,'Valle de la Pascua','Venezuela'),
(109,'Zaraza','Venezuela'),
(110,'Altagracia de Orituco','Venezuela'),
(111,'Carora','Venezuela'),
(112,'Puerto Cabello','Venezuela'),
(113,'Maiquetia','Venezuela'),
(114,'Ocumare del Tuy','Venezuela'),
(115,'Calabozo','Venezuela'),
(116,'Acarigua','Venezuela'),
(117,'Cabimas','Venezuela'),
(118,'Santa Rita','Venezuela'),
(119,'San Carlos del Zulia','Venezuela'),
(120,'Machiques','Venezuela'),
(121,'Valera','Venezuela'),
(122,'Punto Fijo','Venezuela'),
(123,'Carupano','Venezuela'),
(124,'Kingoonya','Australia'),
(125,'Port Denison','Australia'),
(126,'Cairns','Australia'),
(127,'Kwinana','Australia'),
(128,'Cranbourne','Australia'),
(129,'Port Hedland','Australia'),
(130,'Port Lincoln','Australia'),
(131,'Port Macquarie','Australia'),
(132,'Port Pirie','Australia'),
(133,'Portland','Australia'),
(134,'Proserpine','Australia'),
(135,'Busselton','Australia'),
(136,'Caboolture','Australia'),
(137,'Cooma','Australia'),
(138,'Streaky Bay','Australia'),
(139,'Sunbury','Australia'),
(140,'Sydney','Australia'),
(141,'Karumba','Australia'),
(142,'Esperance','Australia'),
(143,'Exmouth','Australia'),
(144,'Forbes','Australia'),
(145,'Morawa','Australia'),
(146,'Moree','Australia'),
(147,'Katherine','Australia'),
(148,'Katoomba','Australia'),
(149,'Launceston','Australia'),
(150,'Laverton','Australia'),
(151,'Leeton','Australia'),
(152,'Leonara','Australia'),
(153,'Seymour','Australia'),
(154,'Singleton','Australia'),
(155,'Newcastle','Australia'),
(156,'Norseman','Australia'),
(157,'Batemans Bay','Australia'),
(158,'Bathurst','Australia'),
(159,'Griffith','Australia'),
(160,'Whyalla','Australia'),
(161,'Wilcannia','Australia'),
(162,'Katanning','Australia'),
(163,'Bongaree','Australia'),
(164,'Bordertown','Australia'),
(165,'Boulia','Australia'),
(166,'Bourke','Australia'),
(167,'Mackay','Australia'),
(168,'Southern Cross','Australia'),
(169,'Ulladulla','Australia'),
(170,'Victor Harbor','Australia'),
(171,'Andamooka','Australia'),
(172,'Hervey Bay','Australia'),
(173,'Gunnedah','Australia'),
(174,'Gympie','Australia'),
(175,'Halls Creek','Australia'),
(176,'Hamilton','Australia'),
(177,'Winton','Australia'),
(178,'Mudgee','Australia'),
(179,'Ivanhoe','Australia'),
(180,'Pannawonica','Australia'),
(181,'Dubbo','Australia'),
(182,'Tom Price','Australia'),
(183,'Parkes','Australia'),
(184,'Sale','Australia'),
(185,'Bendigo','Australia'),
(186,'Berri','Australia'),
(187,'Adelaide','Australia'),
(188,'Adelaide River','Australia'),
(189,'Albany','Australia'),
(190,'Burketown','Australia'),
(191,'Burnie','Australia'),
(192,'Penola','Australia'),
(193,'Perth','Australia'),
(194,'Peterborough','Australia'),
(195,'Scone','Australia'),
(196,'Scottsdale','Australia'),
(197,'Narrabri','Australia'),
(198,'Narrogin','Australia'),
(199,'Townsville','Australia'),
(200,'Traralgon','Australia'),
(201,'Central Coast','Australia'),
(202,'Broome','Australia'),
(203,'Bunbury','Australia'),
(204,'Wyndham','Australia'),
(205,'Yamba','Australia'),
(206,'Tumby Bay','Australia'),
(207,'Forster-Tuncurry','Australia'),
(208,'Bundaberg','Australia'),
(209,'Yulara','Australia'),
(210,'Richmond','Australia'),
(211,'Richmond','Australia'),
(212,'Rockhampton','Australia'),
(213,'Roebourne','Australia'),
(214,'Roma','Australia'),
(215,'Cloncurry','Australia'),
(216,'Cobram','Australia'),
(217,'Coffs Harbour','Australia'),
(218,'Colac','Australia'),
(219,'Alice Springs','Australia'),
(220,'Ararat','Australia'),
(221,'Carnarvon','Australia'),
(222,'Ceduna','Australia'),
(223,'Charleville','Australia'),
(224,'Charters Towers','Australia'),
(225,'Kalbarri','Australia'),
(226,'Kununurra','Australia'),
(227,'Dalby','Australia'),
(228,'Lithgow','Australia'),
(229,'Manjimup','Australia'),
(230,'Maitland','Australia'),
(231,'Mandurah','Australia'),
(232,'Karratha','Australia'),
(233,'Gawler','Australia'),
(234,'Geelong','Australia'),
(235,'Georgetown','Australia'),
(236,'Geraldton','Australia'),
(237,'Maryborough','Australia'),
(238,'Maryborough','Australia'),
(239,'McMinns Lagoon','Australia'),
(240,'Toowoomba','Australia'),
(241,'Onslow','Australia'),
(242,'Orange','Australia'),
(243,'Stawell','Australia'),
(244,'Echuca','Australia'),
(245,'Eidsvold','Australia'),
(246,'Emerald','Australia'),
(247,'Tamworth','Australia'),
(248,'Taree','Australia'),
(249,'Ballarat','Australia'),
(250,'Ballina','Australia'),
(251,'Barcaldine','Australia'),
(252,'Mount Barker','Australia'),
(253,'Mount Gambier','Australia'),
(254,'Mount Isa','Australia'),
(255,'Mount Magnet','Australia'),
(256,'Kempsey','Australia'),
(257,'Queanbeyan','Australia'),
(258,'Queenstown','Australia'),
(259,'Quilpie','Australia'),
(260,'Ravensthorpe','Australia'),
(261,'Warrnambool','Australia'),
(262,'Warwick','Australia'),
(263,'Weipa','Australia'),
(264,'Ouyen','Australia'),
(265,'Wollongong','Australia'),
(266,'Wonthaggi','Australia'),
(267,'Kiama','Australia'),
(268,'Kimba','Australia'),
(269,'Kingaroy','Australia'),
(270,'Pine Creek','Australia'),
(271,'Hobart','Australia'),
(272,'Darwin','Australia'),
(273,'Gingin','Australia'),
(274,'Meekatharra','Australia'),
(275,'Melbourne','Australia'),
(276,'Woomera','Australia'),
(277,'Moranbah','Australia'),
(278,'Port Augusta','Australia'),
(279,'Port Douglas','Australia'),
(280,'Gladstone','Australia'),
(281,'Gold Coast','Australia'),
(282,'Horsham','Australia'),
(283,'Hughenden','Australia'),
(284,'Northam','Australia'),
(285,'Nowra','Australia'),
(286,'Shepparton','Australia'),
(287,'Yeppoon','Australia'),
(288,'Young','Australia'),
(289,'Caloundra','Australia'),
(290,'Ingham','Australia'),
(291,'Innisfail','Australia'),
(292,'Inverell','Australia'),
(293,'Kingston','Australia'),
(294,'Kingston South East','Australia'),
(295,'Clare','Australia'),
(296,'Bowen','Australia'),
(297,'Melton','Australia'),
(298,'Meningie','Australia'),
(299,'Merimbula','Australia'),
(300,'Merredin','Australia'),
(301,'Mildura','Australia'),
(302,'Thargomindah','Australia'),
(303,'Theodore','Australia'),
(304,'Three Springs','Australia'),
(305,'Oatlands','Australia'),
(306,'Wagin','Australia'),
(307,'Armidale','Australia'),
(308,'Atherton','Australia'),
(309,'Ayr','Australia'),
(310,'Bairnsdale','Australia'),
(311,'Camooweal','Australia'),
(312,'Canberra','Australia'),
(313,'Longreach','Australia'),
(314,'Brisbane','Australia'),
(315,'Devonport','Australia'),
(316,'Wallaroo','Australia'),
(317,'Wangaratta','Australia'),
(318,'Cowell','Australia'),
(319,'Cowra','Australia'),
(320,'Goondiwindi','Australia'),
(321,'Goulburn','Australia'),
(322,'Grafton','Australia'),
(323,'Murray Bridge','Australia'),
(324,'Muswellbrook','Australia'),
(325,'Windorah','Australia'),
(326,'Bedourie','Australia'),
(327,'Newman','Australia'),
(328,'Birdsville','Australia'),
(329,'Kalgoorlie','Australia'),
(330,'Biloela','Australia'),
(331,'Smithton','Australia'),
(332,'Bicheno','Australia'),
(333,'Deniliquin','Australia'),
(334,'Broken Hill','Australia'),
(335,'Swan Hill','Australia'),
(336,'Albury','Australia'),
(337,'Wagga Wagga','Australia'),
(338,'Tumut','Australia'),
(339,'Lismore','Australia'),
(340,'Byron Bay','Australia'),
(341,'Tweed Heads','Australia'),
(342,'Selkirk','Canada'),
(343,'Trepassey','Canada'),
(344,'Schefferville','Canada'),
(345,'Whitehorse','Canada'),
(346,'Trout River','Canada'),
(347,'Yorkton','Canada'),
(348,'Antigonish','Canada'),
(349,'Gander','Canada'),
(350,'Berens River','Canada'),
(351,'Port-Menier','Canada'),
(352,'Wetaskiwin','Canada'),
(353,'Shamattawa','Canada'),
(354,'Steinbach','Canada'),
(355,'Thunder Bay','Canada'),
(356,'Oshawa','Canada'),
(357,'Chicoutimi','Canada'),
(358,'Melville','Canada'),
(359,'Brooks','Canada'),
(360,'Dauphin','Canada'),
(361,'Smithers','Canada'),
(362,'Terrace','Canada'),
(363,'Lutselke','Canada'),
(364,'Resolute','Canada'),
(365,'Quesnel','Canada'),
(366,'Island Lake','Canada'),
(367,'Halifax','Canada'),
(368,'Watson Lake','Canada'),
(369,'Sydney','Canada'),
(370,'Dawson Creek','Canada'),
(371,'Uranium City','Canada'),
(372,'Timmins','Canada'),
(373,'Saskatoon','Canada'),
(374,'Iqaluit','Canada'),
(375,'Alert','Canada'),
(376,'Thessalon','Canada'),
(377,'Yellowknife','Canada'),
(378,'Camrose','Canada'),
(379,'Campbell River','Canada'),
(380,'Revelstoke','Canada'),
(381,'Meadow Lake','Canada'),
(382,'Atikokan','Canada'),
(383,'Creston','Canada'),
(384,'Gillam','Canada'),
(385,'Cranbrook','Canada'),
(386,'Little Current','Canada'),
(387,'Calgary','Canada'),
(388,'Big Beaver House','Canada'),
(389,'Parry Sound','Canada'),
(390,'Kamloops','Canada'),
(391,'Dolbeau','Canada'),
(392,'St. Johns','Canada'),
(393,'Lansdowne House','Canada'),
(394,'Paulatuk','Canada'),
(395,'Attawapiskat','Canada'),
(396,'Rimouski','Canada'),
(397,'Grand Prairie','Canada'),
(398,'La Sarre','Canada'),
(399,'Mingan','Canada'),
(400,'Prince Albert','Canada'),
(401,'Moose Jaw','Canada'),
(402,'Powell River','Canada'),
(403,'Pangnirtung','Canada'),
(404,'Nelson','Canada'),
(405,'Peace River','Canada'),
(406,'Cobalt','Canada'),
(407,'New Glasgow','Canada'),
(408,'Arctic Bay','Canada'),
(409,'Burwash Landing','Canada'),
(410,'Saint-Georges','Canada'),
(411,'Vancouver','Canada'),
(412,'Medicine Hat','Canada'),
(413,'Port Hope Simpson','Canada'),
(414,'Deer Lake','Canada'),
(415,'Vegreville','Canada'),
(416,'Bella Bella','Canada'),
(417,'Rankin Inlet','Canada'),
(418,'Owen Sound','Canada'),
(419,'Lac La Biche','Canada'),
(420,'Hopedale','Canada'),
(421,'Norway House','Canada'),
(422,'Coral Harbour','Canada'),
(423,'Kugluktuk','Canada'),
(424,'Norman Wells','Canada'),
(425,'Fort Resolution','Canada'),
(426,'Fort McPherson','Canada'),
(427,'Forteau','Canada'),
(428,'Kuujjuaq','Canada'),
(429,'Cape Dorset','Canada'),
(430,'Cartwright','Canada'),
(431,'Flin Flon','Canada'),
(432,'Holman','Canada'),
(433,'Pembroke','Canada'),
(434,'Baker Lake','Canada'),
(435,'Moosonee','Canada'),
(436,'Dryden','Canada'),
(437,'Corner Brook','Canada'),
(438,'Kelowna','Canada'),
(439,'Fort Smith','Canada'),
(440,'Fort Severn','Canada'),
(441,'Mont-Laurier','Canada'),
(442,'Channel-Port aux Basques','Canada'),
(443,'Kindersley','Canada'),
(444,'Igloolik','Canada'),
(445,'Hudson Bay','Canada'),
(446,'Courtenay','Canada'),
(447,'Mistassini','Canada'),
(448,'Kingston','Canada'),
(449,'Eastmain','Canada'),
(450,'Baie-Comeau','Canada'),
(451,'North Bay','Canada'),
(452,'North Battleford','Canada'),
(453,'Grise Fiord','Canada'),
(454,'Hay River','Canada'),
(455,'Stony Rapids','Canada'),
(456,'Hinton','Canada'),
(457,'Toronto','Canada'),
(458,'Edmonton','Canada'),
(459,'Gjoa Haven','Canada'),
(460,'Fort Simpson','Canada'),
(461,'Naujaat','Canada'),
(462,'Lethbridge','Canada'),
(463,'Sudbury','Canada'),
(464,'Swift Current','Canada'),
(465,'Regina','Canada'),
(466,'Cornwall','Canada'),
(467,'Taloyoak','Canada'),
(468,'Tuktoyaktuk','Canada'),
(469,'Deer Lake','Canada'),
(470,'London','Canada'),
(471,'Natashquan','Canada'),
(472,'Cap-Chat','Canada'),
(473,'Orillia','Canada'),
(474,'Kenora','Canada'),
(475,'Barrie','Canada'),
(476,'Sherbrooke','Canada'),
(477,'St. Anthony','Canada'),
(478,'Rigolet','Canada'),
(479,'Fort Good Hope','Canada'),
(480,'La Scie','Canada'),
(481,'Fort St. John','Canada'),
(482,'Marathon','Canada'),
(483,'Gaspe','Canada'),
(484,'Nelson House','Canada'),
(485,'Lillooet','Canada'),
(486,'Fort McMurray','Canada'),
(487,'Jasper','Canada'),
(488,'Buchans','Canada'),
(489,'Stettler','Canada'),
(490,'La Ronge','Canada'),
(491,'Brochet','Canada'),
(492,'Baddeck','Canada'),
(493,'Pond Inlet','Canada'),
(494,'St-Augustin','Canada'),
(495,'Gimli','Canada'),
(496,'Red Lake','Canada'),
(497,'Stephenville','Canada'),
(498,'Ennadai','Canada'),
(499,'Happy Valley - Goose Bay','Canada'),
(500,'Williams Lake','Canada'),
(501,'Prince Rupert','Canada'),
(502,'Chilliwack','Canada'),
(503,'Radisson','Canada'),
(504,'Churchill','Canada'),
(505,'Port Hardy','Canada'),
(506,'Penticton','Canada'),
(507,'Drummondville','Canada'),
(508,'Brandon','Canada'),
(509,'Argentia','Canada'),
(510,'Kimmirut','Canada'),
(511,'Wiarton','Canada'),
(512,'Ottawa','Canada'),
(513,'Fort Chipewyan','Canada'),
(514,'Fort Nelson','Canada'),
(515,'Lynn Lake','Canada'),
(516,'Weyburn','Canada'),
(517,'Burns Lake','Canada'),
(518,'Nain','Canada'),
(519,'Prince George','Canada'),
(520,'Cochrane','Canada'),
(521,'Nipigon','Canada'),
(522,'Riviere-du-Loup','Canada'),
(523,'St.-Jerome','Canada'),
(524,'Geraldton','Canada'),
(525,'New Liskeard','Canada'),
(526,'Cat Lake','Canada'),
(527,'Tofino','Canada'),
(528,'Tsiigehtchic','Canada'),
(529,'Thompson','Canada'),
(530,'Abbotsford','Canada'),
(531,'Trois-Rivieres','Canada'),
(532,'Peterborough','Canada'),
(533,'Amos','Canada'),
(534,'Chapleau','Canada'),
(535,'Athabasca','Canada'),
(536,'Red Deer','Canada'),
(537,'Belleville','Canada'),
(538,'Kapuskasing','Canada'),
(539,'Sioux Lookout','Canada'),
(540,'Winnipeg','Canada'),
(541,'Lake Louise','Canada'),
(542,'Banff','Canada'),
(543,'Doline','Canada'),
(544,'Cambridge Bay','Canada'),
(545,'Biggar','Canada'),
(546,'Nanaimo','Canada'),
(547,'Val dOr','Canada'),
(548,'Hall Beach','Canada'),
(549,'Oxford House','Canada'),
(550,'The Pas','Canada'),
(551,'Meander River','Canada'),
(552,'Bathurst','Canada'),
(553,'Windsor','Canada'),
(554,'Victoriaville','Canada'),
(555,'Brockville','Canada'),
(556,'Hamilton','Canada'),
(557,'Kitchener','Canada'),
(558,'Victoria','Canada'),
(559,'Orangeville','Canada'),
(560,'Sandspit','Canada'),
(561,'Wawa','Canada'),
(562,'Kangirsuk','Canada'),
(563,'Shawinigan','Canada'),
(564,'Hearst','Canada'),
(565,'Pukatawagan','Canada'),
(566,'Arviat','Canada'),
(567,'Matagami','Canada'),
(568,'Saint John','Canada'),
(569,'Inuvik','Canada'),
(570,'Chesterfield Inlet','Canada'),
(571,'Rouyn-Noranda','Canada'),
(572,'Liverpool','Canada'),
(573,'Montreal','Canada'),
(574,'Shelburne','Canada'),
(575,'Yarmouth','Canada'),
(576,'Salluit','Canada'),
(577,'Ivugivik','Canada'),
(578,'Quebec','Canada'),
(579,'Dawson City','Canada'),
(580,'Moncton','Canada'),
(581,'Digby','Canada'),
(582,'Fredericton','Canada'),
(583,'Dease Lake','Canada'),
(584,'Charlottetown','Canada'),
(585,'Inukjuak','Canada'),
(586,'Sarnia','Canada'),
(587,'Edmundston','Canada'),
(588,'Windsor','Canada'),
(589,'Joliette','Canada'),
(590,'Amherst','Canada'),
(591,'Sept-Iles','Canada'),
(592,'Warrington','United Kingdom'),
(593,'Newbury','United Kingdom'),
(594,'Swindon','United Kingdom'),
(595,'Wick','United Kingdom'),
(596,'Dudley','United Kingdom'),
(597,'Oxford','United Kingdom'),
(598,'Hackney','United Kingdom'),
(599,'Matlock','United Kingdom'),
(600,'Lochgilphead','United Kingdom'),
(601,'Northallerton','United Kingdom'),
(602,'Edinburgh','United Kingdom'),
(603,'Sunderland','United Kingdom'),
(604,'Swansea','United Kingdom'),
(605,'Wokingham','United Kingdom'),
(606,'City of Westminster','United Kingdom'),
(607,'Solihull','United Kingdom'),
(608,'Rochdale','United Kingdom'),
(609,'Nottingham','United Kingdom'),
(610,'Winchester','United Kingdom'),
(611,'Wembley','United Kingdom'),
(612,'Motherwell','United Kingdom'),
(613,'Reading','United Kingdom'),
(614,'Torquay','United Kingdom'),
(615,'Thornbury','United Kingdom'),
(616,'Oldham','United Kingdom'),
(617,'Elgin','United Kingdom'),
(618,'Wallsend','United Kingdom'),
(619,'Weston-super-Mare','United Kingdom'),
(620,'Hounslow','United Kingdom'),
(621,'Irvine','United Kingdom'),
(622,'Barnsley','United Kingdom'),
(623,'Falkirk','United Kingdom'),
(624,'Slough','United Kingdom'),
(625,'Huddersfield','United Kingdom'),
(626,'Kingston upon Hull','United Kingdom'),
(627,'Romford','United Kingdom'),
(628,'Grays','United Kingdom'),
(629,'Hertford','United Kingdom'),
(630,'Coventry','United Kingdom'),
(631,'Leicester','United Kingdom'),
(632,'Beverley','United Kingdom'),
(633,'Stirling','United Kingdom'),
(634,'Norwich','United Kingdom'),
(635,'Darlington','United Kingdom'),
(636,'Hereford','United Kingdom'),
(637,'Grimsby','United Kingdom'),
(638,'Bradford','United Kingdom'),
(639,'Bracknell','United Kingdom'),
(640,'Morpeth','United Kingdom'),
(641,'Gateshead','United Kingdom'),
(642,'Wandsworth','United Kingdom'),
(643,'South Shields','United Kingdom'),
(644,'Sheffield','United Kingdom'),
(645,'Ystrad Mynach','United Kingdom'),
(646,'South Bank','United Kingdom'),
(647,'Haddington','United Kingdom'),
(648,'Aberaeron','United Kingdom'),
(649,'Lerwick','United Kingdom'),
(650,'Cambridge','United Kingdom'),
(651,'Glenrothes','United Kingdom'),
(652,'Pen-y-Bont ar Ogwr','United Kingdom'),
(653,'Barri','United Kingdom'),
(654,'Carlisle','United Kingdom'),
(655,'Aylesbury','United Kingdom'),
(656,'Lincoln','United Kingdom'),
(657,'Bromley','United Kingdom'),
(658,'Kirkwall','United Kingdom'),
(659,'Blackpool','United Kingdom'),
(660,'Croydon','United Kingdom'),
(661,'Dorchester','United Kingdom'),
(662,'Hendon','United Kingdom'),
(663,'Hammersmith','United Kingdom'),
(664,'Bournemouth','United Kingdom'),
(665,'Fort William','United Kingdom'),
(666,'Dumfries','United Kingdom'),
(667,'Dumbarton','United Kingdom'),
(668,'Luton','United Kingdom'),
(669,'Bristol','United Kingdom'),
(670,'Enfield','United Kingdom'),
(671,'Camberwell','United Kingdom'),
(672,'Truro','United Kingdom'),
(673,'Penzance','United Kingdom'),
(674,'Clydach Vale','United Kingdom'),
(675,'Telford','United Kingdom'),
(676,'Stockton-on-Tees','United Kingdom'),
(677,'Maidenhead','United Kingdom'),
(678,'Dalkeith','United Kingdom'),
(679,'Wood Green','United Kingdom'),
(680,'Pont-y-pwl','United Kingdom'),
(681,'Perth','United Kingdom'),
(682,'Milton Keynes','United Kingdom'),
(683,'Hartlepool','United Kingdom'),
(684,'Harrow','United Kingdom'),
(685,'Oldbury','United Kingdom'),
(686,'Ashton-under-Lyne','United Kingdom'),
(687,'Wakefield','United Kingdom'),
(688,'Trowbridge','United Kingdom'),
(689,'Maidstone','United Kingdom'),
(690,'Poole','United Kingdom'),
(691,'Newport','United Kingdom'),
(692,'Walsall','United Kingdom'),
(693,'Woolwich','United Kingdom'),
(694,'Southend-on-Sea','United Kingdom'),
(695,'Scunthorpe','United Kingdom'),
(696,'Caernarfon','United Kingdom'),
(697,'Hamilton','United Kingdom'),
(698,'Durham','United Kingdom'),
(699,'Warwick','United Kingdom'),
(700,'Aberdeen','United Kingdom'),
(701,'Newtown Saint Boswells','United Kingdom'),
(702,'Sutton','United Kingdom'),
(703,'Catford','United Kingdom'),
(704,'Lambeth','United Kingdom'),
(705,'Lewes','United Kingdom'),
(706,'Dundee','United Kingdom'),
(707,'Ipswich','United Kingdom'),
(708,'Birmingham','United Kingdom'),
(709,'Stoke','United Kingdom'),
(710,'Stockport','United Kingdom'),
(711,'Chelmsford','United Kingdom'),
(712,'Leeds','United Kingdom'),
(713,'Bath','United Kingdom'),
(714,'Ayr','United Kingdom'),
(715,'Kirkintilloch','United Kingdom'),
(716,'Wallasey','United Kingdom'),
(717,'Conwy','United Kingdom'),
(718,'Rhuthun','United Kingdom'),
(719,'Walthamstow','United Kingdom'),
(720,'Halifax','United Kingdom'),
(721,'Peterborough','United Kingdom'),
(722,'Rotherham','United Kingdom'),
(723,'Alloa','United Kingdom'),
(724,'Southampton','United Kingdom'),
(725,'Ebbw Vale','United Kingdom'),
(726,'Forfar','United Kingdom'),
(727,'Islington','United Kingdom'),
(728,'Caerfyrddin','United Kingdom'),
(729,'Ealing','United Kingdom'),
(730,'Kilmarnock','United Kingdom'),
(731,'Newport','United Kingdom'),
(732,'Kensington','United Kingdom'),
(733,'Hwlffordd','United Kingdom'),
(734,'Uxbridge','United Kingdom'),
(735,'Twickenham','United Kingdom'),
(736,'Plymouth','United Kingdom'),
(737,'Livingston','United Kingdom'),
(738,'Portsmouth','United Kingdom'),
(739,'Paisley','United Kingdom'),
(740,'Exeter','United Kingdom'),
(741,'Widnes','United Kingdom'),
(742,'Stretford','United Kingdom'),
(743,'Stornoway','United Kingdom'),
(744,'Manchester','United Kingdom'),
(745,'Inverness','United Kingdom'),
(746,'Morden','United Kingdom'),
(747,'London','United Kingdom'),
(748,'Ilford','United Kingdom'),
(749,'Poplar','United Kingdom'),
(750,'Salford','United Kingdom'),
(751,'Derby','United Kingdom'),
(752,'Mold','United Kingdom'),
(753,'Worcester','United Kingdom'),
(754,'Rochester','United Kingdom'),
(755,'Chichester','United Kingdom'),
(756,'East Ham','United Kingdom'),
(757,'Oakham','United Kingdom'),
(758,'Gloucester','United Kingdom'),
(759,'Wrecsam','United Kingdom'),
(760,'Wolverhampton','United Kingdom'),
(761,'Llangefni','United Kingdom'),
(762,'Hove','United Kingdom'),
(763,'Brighton','United Kingdom'),
(764,'Doncaster','United Kingdom'),
(765,'Shrewsbury','United Kingdom'),
(766,'Glasgow','United Kingdom'),
(767,'Camden Town','United Kingdom'),
(768,'Cardiff','United Kingdom'),
(769,'Bexleyheath','United Kingdom'),
(770,'Dover','United Kingdom'),
(771,'Bury','United Kingdom'),
(772,'Greenock','United Kingdom'),
(773,'Middlesbrough','United Kingdom'),
(774,'Scarborough','United Kingdom'),
(775,'Merthyr Tudful','United Kingdom'),
(776,'Taunton','United Kingdom'),
(777,'York','United Kingdom'),
(778,'Port Talbot','United Kingdom'),
(779,'Dagenham','United Kingdom'),
(780,'Liverpool','United Kingdom'),
(781,'Saint Helens','United Kingdom'),
(782,'Knowsley','United Kingdom'),
(783,'Kingston upon Thames','United Kingdom'),
(784,'Wigan','United Kingdom'),
(785,'Southport','United Kingdom'),
(786,'Preston','United Kingdom'),
(787,'Blackburn','United Kingdom'),
(788,'Bolton','United Kingdom'),
(789,'Hugh Town','United Kingdom'),
(790,'Bedford','United Kingdom'),
(791,'Chicksands','United Kingdom'),
(792,'Sandbach','United Kingdom'),
(793,'Chester','United Kingdom'),
(794,'Llandrindod Wells','United Kingdom'),
(795,'Northampton','United Kingdom'),
(796,'Giffnock','United Kingdom'),
(797,'Newcastle','United Kingdom'),
(798,'Downpatrick','United Kingdom'),
(799,'Coleraine','United Kingdom'),
(800,'Magherafelt','United Kingdom'),
(801,'Dungannon','United Kingdom'),
(802,'Cookstown','United Kingdom'),
(803,'Bangor','United Kingdom'),
(804,'Strabane','United Kingdom'),
(805,'Londonderry','United Kingdom'),
(806,'Omagh','United Kingdom'),
(807,'Enniskillen','United Kingdom'),
(808,'Ballymena','United Kingdom'),
(809,'Banbridge','United Kingdom'),
(810,'Armagh','United Kingdom'),
(811,'Newtownabbey','United Kingdom'),
(812,'Craigavon','United Kingdom'),
(813,'Antrim','United Kingdom'),
(814,'Newry','United Kingdom'),
(815,'Lisburn','United Kingdom'),
(816,'Belfast','United Kingdom'),
(817,'Belfast','United Kingdom'),
(818,'Usk','United Kingdom'),
(819,'Stafford','United Kingdom'),
(820,'Muroran','Japan'),
(821,'Iwaki','Japan'),
(822,'Sakata','Japan'),
(823,'Tottori','Japan'),
(824,'Maizuru','Japan'),
(825,'Hamamatsu','Japan'),
(826,'Takaoka','Japan'),
(827,'Asahikawa','Japan'),
(828,'Tsuruoka','Japan'),
(829,'Otaru','Japan'),
(830,'Kawagoe','Japan'),
(831,'Hachioji','Japan'),
(832,'Hirosaki','Japan'),
(833,'Kure','Japan'),
(834,'Hachinohe','Japan'),
(835,'Matsumoto','Japan'),
(836,'Tokyo','Japan'),
(837,'Tomakomai','Japan'),
(838,'Obihiro','Japan'),
(839,'Nagaoka','Japan'),
(840,'Koriyama','Japan'),
(841,'Shimonoseki','Japan'),
(842,'Sasebo','Japan'),
(843,'Kanoya','Japan'),
(844,'Kitakyushu','Japan'),
(845,'Akita','Japan'),
(846,'Aomori','Japan'),
(847,'Chiba','Japan'),
(848,'Fukui','Japan'),
(849,'Fukuoka','Japan'),
(850,'Fukushima','Japan'),
(851,'Gifu','Japan'),
(852,'Hiroshima','Japan'),
(853,'Kagoshima','Japan'),
(854,'Kanazawa','Japan'),
(855,'Kobe','Japan'),
(856,'Kochi','Japan'),
(857,'Kofu','Japan'),
(858,'Kumamoto','Japan'),
(859,'Kyoto','Japan'),
(860,'Maebashi','Japan'),
(861,'Matsue','Japan'),
(862,'Matsuyama','Japan'),
(863,'Mito','Japan'),
(864,'Miyazaki','Japan'),
(865,'Morioka','Japan'),
(866,'Nagano','Japan'),
(867,'Nagasaki','Japan'),
(868,'Nagoya','Japan'),
(869,'Naha','Japan'),
(870,'Niigata','Japan'),
(871,'Oita','Japan'),
(872,'Okayama','Japan'),
(873,'Osaka','Japan'),
(874,'Otsu','Japan'),
(875,'Sapporo','Japan'),
(876,'Sendai','Japan'),
(877,'Shizuoka','Japan'),
(878,'Takamatsu','Japan'),
(879,'Tokushima','Japan'),
(880,'Tottori','Japan'),
(881,'Toyama','Japan'),
(882,'Tsu','Japan'),
(883,'Utsunomiya','Japan'),
(884,'Wakayama','Japan'),
(885,'Yamagata','Japan'),
(886,'Yamaguchi','Japan'),
(887,'Yokohama','Japan'),
(888,'Saitama','Japan'),
(889,'Saga','Japan'),
(890,'Kawasaki','Japan'),
(891,'Nara','Japan'),
(892,'Kushiro','Japan'),
(893,'Kitami','Japan'),
(894,'Hakodate','Japan');
------- grupo 2 ----------

-- INSERT INTO Role (rol_name)
-- VALUES ('Cliente');

-- INSERT INTO Role (rol_name)
-- VALUES ('Administrador');

-- INSERT INTO Role (rol_name)
-- VALUES ('Checkin');

-- INSERT INTO Role (rol_name)
-- VALUES ('Reclamo');

-- INSERT INTO Role (rol_name)
-- VALUES ('Cargador');

INSERT INTO Users(use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('9784673', 'admin@vacanze.com', 'Virtuoso', 'Francisco', MD5('admin123'));

INSERT INTO Users(use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('10754927', 'checkin@vacanze.com', 'Gomes', 'Francisco', MD5('checkin123'));

INSERT INTO Users(use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('12345678', 'reclamo@vacanze.com', 'Omar', 'Jorge', MD5('reclamo123'));

INSERT INTO Users(use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('8654826', 'cargador@vacanze.com', 'Salazar', 'Marcos', MD5('cargador123'));

INSERT INTO Users(use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('20766589', 'cliente@vacanze.com', 'Martinez', 'Carlos', MD5('cliente123'));

INSERT INTO USERS (use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('23613704', 'larry.page@vacanze.com', 'Page', 'Larry', MD5('google'));

INSERT INTO USERS (use_document_id, use_email, use_last_name, use_name, use_password)
VALUES ('23613704', 'reggaebob@vacanze.com', 'Marley', 'Bob', MD5('jah'));

INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (2, 1);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (3, 2);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (4, 3);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (5, 4);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (1, 5);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (1, 6);
INSERT INTO User_Role(usr_rol_id, usr_use_id) VALUES (1, 7);


------- grupo 6 ----------

INSERT INTO hotel (hot_nombre, hot_cant_habitaciones, hot_activo, hot_telefono, hot_sitio_web,
                   hot_fk_lugar)
VALUES ('Hotel 1', 50, TRUE, '1238123', null, 1),
		('Hotel 2', 100, TRUE, '5456465', null, 1),
		('Hotel 3' , 200, TRUE, '54534', null , 2);


-------------------------------Grupo 3---------------------------------------------------
INSERT INTO public.Plane(
	pla_id, pla_autonomy, "pla_isActive", pla_capacity, "pla_loadingCap", pla_model)
	VALUES (nextval('seq_plane'),100,true, 50, 1000, 'Boeing 1');
INSERT INTO public.Plane(
	pla_id, pla_autonomy, "pla_isActive", pla_capacity, "pla_loadingCap", pla_model)
	VALUES (nextval('seq_plane'),150,true, 40, 1000, 'Boeing 2');
INSERT INTO public.Plane(
	pla_id, pla_autonomy, "pla_isActive", pla_capacity, "pla_loadingCap", pla_model)
	VALUES (nextval('seq_plane'),111,true, 30, 1000, 'Boeing 3');
INSERT INTO public.Plane(
	pla_id, pla_autonomy, "pla_isActive", pla_capacity, "pla_loadingCap", pla_model)
	VALUES (nextval('seq_plane'),200,true, 50, 2000, 'Boeing 4');
INSERT INTO public.Plane(
	pla_id, pla_autonomy, "pla_isActive", pla_capacity, "pla_loadingCap", pla_model)
	VALUES (nextval('seq_plane'),80,true, 10, 1000, 'Boeing 5');
	
	
--------------Grupo 8 ---------------------------------
INSERT INTO Ship(shi_id, shi_name, shi_capacity ,shi_loadingcap, shi_model,shi_line, shi_picture ) VALUES (default, 'concordia', 100, 1000, 'Modelo1','Linea1', '1.jpg' );
INSERT INTO Ship(shi_id, shi_name, shi_capacity ,shi_loadingcap, shi_model,shi_line, shi_picture ) VALUES (default, 'Lmao', 500, 2000, 'Modelo2','Linea2', '3.jpg' );

------- grupo 10 ----------

INSERT INTO Travel(tra_name, tra_descr, tra_use_fk)
VALUES ('Surf Trip', 'Surf trip arroud Vnzla', 5);

INSERT INTO Travel(tra_name, tra_descr, tra_use_fk)
VALUES ('Family', 'Summer Vacation', 5);

INSERT INTO Travel(tra_name, tra_descr, tra_use_fk)
VALUES ('Business Trip', 'About businnes, I am busy', 6);
